# Nightly Build & Pre-release
name: "Nightly"

on:
  push:
    branches:
      - master
  workflow_dispatch:
  # Uncomment to enable scheduled runs, if desired:
  # schedule:
  #   - cron: '0 5 * * *'

env:
  NIGHTLY_TAG: "coral-in-progress"
  NIGHTLY_NAME: "coral-in-progress"
  NIGHTLY_BODY: |
    This is the current Polished Coral *beta* release.

jobs:
  build:
    name: "Nightly"
    uses: OngoGablogian/polishedcoral/.github/workflows/build.yml@master

  release:
    name: "Nightly / Release"
    # Only proceed with the release job if this is the official repository (not a fork)
    if: ${{ github.repository_owner == 'OngoGablogian' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # SET ENVIRONMENT VARIABLES
      - id: set-env-var
        name: "Set environment variables"
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      # INSTALL DEPENDENCIES
      - id: apt-get-depends
        name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install bison gcc git make -y;

      # CHECKOUT REPOSITORY
      - id: checkout-polishedcoral
        name: "Checkout OngoGablogian/polishedcoral"
        uses: actions/checkout@v4

      # DOWNLOAD ALL BUILD ARTIFACTS
      - id: download-polishedcoral
        name: "Download polishedcoral"
        uses: actions/download-artifact@v4.1.7
        with:
          name: "polishedcoral"
          path: "./build"

      # DELETE OLD RELEASE
      - name: Delete old release
        id: delete_release
        uses: cb80/delrel@latest
        with:
          tag: ${{ env.NIGHTLY_TAG }}

      # ADVANCE NIGHTLY TAG TO MASTER
      - name: Advance nightly tag to master
        run: |
          git tag ${{ env.NIGHTLY_TAG }} -f
          git push --tags -f "https://OngoGablogian:$GITHUB_TOKEN@github.com/OngoGablogian/polishedcoral.git"

      # CREATE NEW RELEASE
      - name: Create new release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NIGHTLY_TAG }}
          name: ${{ env.NIGHTLY_NAME }}
          body: ${{ env.NIGHTLY_BODY }}
          draft: false
          prerelease: true

      # UPLOAD POLISHED CORAL ASSETS
      - name: Upload regular assets
        id: upload
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NIGHTLY_TAG }}
          files: |
            ./build/coral-in-progress-${{ env.SHORT_SHA }}.gbc
